version: "3"
services:

#  consumer01:
#    container_name: dbsync-consumer01
#    restart: always
#    image: consumer:latest
#    ports:
#      - "8081:8080"
#    networks:
#      - net
#
#  consumer02:
#    container_name: dbsync-consumer02
#    restart: always
#    image: consumer:latest
#    ports:
#      - "8082:8080"
#    networks:
#      - net
#
#  consumer03:
#    container_name: dbsync-consumer03
#    restart: always
#    image: consumer:latest
#    ports:
#      - "8083:8080"
#    networks:
#      - net

  zookeeper:
    container_name: dbsync-zookeeper
    restart: always
    image: quay.io/debezium/zookeeper:1.9
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - net

  kafka:
    container_name: dbsync-kafka
    restart: always
    image: quay.io/debezium/kafka:1.9
    ports:
      - "9092:9092"
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      # Kafka Listener 설정
      # https://taaewoo.tistory.com/59
      # https://velog.io/@6democratickim9/How-To-Use-%EC%B9%B4%ED%94%84%EC%B9%B4-%EB%8F%84%EC%BB%A4-%EC%9D%B4%EB%AF%B8%EC%A7%80
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - net

  mysql:
    container_name: dbsync-mysql
    restart: always
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1q2w3e4r!"
      MYSQL_DATABASE: "study"
    networks:
      - net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    container_name: kafka-ui
    ports:
      - "7070:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=localhost
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - net

networks:
  net:
    driver: bridge